[theme]
base = "light"
primaryColor = "#005F4F"
backgroundColor = "#DCEBE7"
secondaryBackgroundColor = "#C8DEDA"
textColor = "#183430"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#005F4F"
secondaryBackgroundColor = "#004F5F"
textColor = "#FFFFFF"
primaryColor = "#FFFFFF"
